# Generated by Django 4.2.2 on 2023-07-03 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_pbpm_delete_pbm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pbpm',
            old_name='pmt',
            new_name='overhead_per_ten_mt',
        ),
    ]
