from django.db import models

# Create your models here.
    
class PBPM(models.Model):
    commodity = models.CharField(max_length=50)
    ft = models.IntegerField(("FT"))
    rate = models.FloatField()
    rent = models.IntegerField()
    rent_per_mt = models.FloatField()
    allway_space = models.IntegerField()
    net_space = models.IntegerField()
    bag_size = models.IntegerField()
    space_per_bag = models.FloatField()
    stack_ht = models.IntegerField()
    utilisation = models.FloatField()
    wh_capacity = models.FloatField()
    value_per_bag = models.IntegerField()
    whs = models.IntegerField()
    whs_per_mt = models.FloatField()
    sg = models.IntegerField()
    sg_per_mt = models.FloatField()
    other = models.IntegerField()
    no_of_bag_utilization = models.IntegerField()
    utilize_mt = models.IntegerField()
    total_value = models.IntegerField()
    insurance = models.IntegerField()
    insurance_per_month = models.IntegerField()
    insurance_per_mt = models.FloatField()
    fumigation = models.IntegerField()
    # pmt = models.IntegerField()
    fumigation_per_mt = models.IntegerField()
    overhead_per_ten_mt = models.IntegerField()
    overhead_per_mt = models.IntegerField()
    total_cost = models.IntegerField()
    cost_per_bag = models.FloatField()
    profit = models.FloatField()
    base_rate_pbpm = models.FloatField()
    base_rate_per_mt = models.FloatField()
    profit_in_mt = models.FloatField()
    base_rate_pmt = models.FloatField()
    commodity_rate = models.IntegerField()